apiVersion: apps/v1
kind: Deployment
metadata:
  name: covidtracker-bayan-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: covidtracker-bayan-app
  template:
    metadata:
      labels:
        app: covidtracker-bayan-app
    spec:
      containers:
        - name: covidtracker-bayan-container
          image: bayanaltaleb/covidtracker-bayan:6.0
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: covidtracker-bayan-deployment
  labels:
    app: covidtracker-bayan-app
spec:
  ports:
  - port: 3000
  selector:
    app: covidtracker-bayan-app
