apiVersion: apps/v1
kind: Deployment
metadata:
  name: covidtracker-bayan-pod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: covidtracker-bayan-app
  template:
    metadata:
      labels:
        app: covidtracker-bayan-app
    spec:
      containers:
        - name: covidtracker-bayan-container
          image: bayanaltaleb/covidtracker-bayan:6.0
          ports:
            - containerPort: 80
